### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Dontmindmes** [yumere/Twitter-Ransomware#1]
which one of the .py files to start compile

**Comment by yumere** [comment]
@Dontmindmes Oh Sorry, This repository is just for storing code.
Nevertheless you want to run the code, See this [LBP.py](https://github.com/yumere/Twitter-Ransomware/blob/master/GraphicalInference/LBP.py) or [LPs.py](https://github.com/yumere/Twitter-Ransomware/blob/master/GraphicalInference/LPs.py).

In order to run the code, You may need tweets data as shown below.

```
[
  {
    'body': 'tweets body',
    'posted_time': datetime,
    'label': 'related' or 'not related',
    'word_embeddings': np.ndarray: (word_len, dim)
  },
  { ... }
]
```

Thank you.
